[project]
name = "shellagent"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "keyboard>=0.13.5",
    "pyperclip>=1.9.0",
    "pywin32>=311",
    "requests>=2.32.5",
]
